#!/usr/bin/env bash
# This script displays information about subdomains of a domain

get_subdomain_info() {
    local main_domain="$1"
    local sub_domain="$2"

    line=$(dig "$sub_domain"."$main_domain" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$sub_domain $line" | awk '{print "Subdomain " $1 " is a " $2 " record and points to " $3}'
}

# Check if domain argument is provided
if [ "$#" == 1 ]; then
    get_subdomain_info "$1" "www"
    get_subdomain_info "$1" "lb-01"
    get_subdomain_info "$1" "web-01"
    get_subdomain_info "$1" "web-02"
elif [ "$#" == 2 ]; then
    get_subdomain_info "$1" "$2"
fi
