#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing
# Nginx to listen on port 80 and serve a page with "Hello World!"

echo -e "Updating and installing Nginx...\n"
sudo apt-get update -y -qq && \
sudo apt-get install nginx -y

echo -e "\nSetting up Nginx to listen on port 80...\n"

# Replace default Nginx HTML file with "Hello World!"
echo -e "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Restart Nginx without using systemctl
sudo /etc/init.d/nginx restart

echo -e "\nCompleted. ✅\n"
