#!/usr/bin/env bash
# Configures a new Ubuntu machine with Nginx
# Includes redirection from /redirect_me to another page

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
sudo apt-get install nginx -y

echo -e "\nSetting up Nginx and redirection.\n"

# Create a custom Nginx configuration file for redirection
echo "server {
	listen 80;

	ubuntu;

	location /redirect_me {
	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}

}" | sudo tee /etc/nginx/sites-available/redirect_me > /dev/null

# Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Remove default Nginx site
sudo rm -f /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart

echo -e "\nCompleted. \n"
