#!/usr/bin/env bash
# This script takes a MySQL root password as an argument, performs a database backup.
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
