#!/usr/bin/env bash

# This script fixes the Nginx configuration to make it listen on port 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
