#!/usr/bin/env bash
# This script fixes the Nginx configuration to make it listen on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
echo "" > /run/nginx.pid
