#!/usr/bin/env bash
#Script that displays "Best School" 10 times.
#   "bad luck" for the 4th output.
#   "good luck" for the 8th output.

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
