#!/usr/bin/env bash
#Script that displays numbers from 1 to 20 and:
#   "bad luck from china" for the 4th output.
#   "bad luck from japan" for the 4th output.
#   "bad luck from italy" for the 17th output.

i=1

while [ $i -le 20 ]
do
	echo "$i"
	case $i in 
		"4") echo "bad luck from china";;
		"9") echo "bad luck from japan";;
		"17") echo "bad luck from italy";;
	esac
	((i++))
done
