#!/usr/bin/env bash
# Reload Gunicorn in a graceful way.


# Find Gunicorn process
gunicorn_pids=$(pgrep gunicorn)

if [ -z "$gunicorn_pids" ]; then
    echo "No Gunicorn processes found."
    exit 1
fi

# Stop old workers
echo "Stopping old workers gracefully..."
for pid in $gunicorn_pids; do
    kill -HUP "$pid"
done

# Wait for old workers to finish
echo "Waiting for old workers to finish processing..."
wait

echo "Graceful reload complete"

