#!/usr/bin/env bash
# Reload Gunicorn in a graceful way.

gunicorn_pids=$(pgrep gunicorn)

if [ -z "$gunicorn_pids" ]; then
    echo "No Gunicorn processes found."
    exit 1
fi

echo "Stopping old workers gracefully..."
for pid in $gunicorn_pids; do
    kill -HUP "$pid"
done

echo "Waiting for old workers to finish processing..."
wait

echo "Graceful reload complete"

